/* ============================================================
   papers.js : 논문 목록 (Publications)
   ------------------------------------------------------------
   논문 한 편 = 아래 형식의 한 줄입니다. 쉼표(,)를 꼭 남겨두세요.

   { n: 89, y: 2026, ref: "J. Am. Chem. Soc. 2026, 148, 1234-1240",
     t: "논문 제목", a: "First Author*, Second Author, Dong Young Chung", c: true },

   n    : 논문 번호 (출판된 논문만. 가장 최근 논문이 가장 큰 번호)
   y    : 출판 연도 숫자 (미출판 논문은 "pending" 따옴표 포함)
   ref  : 저널, 연도, 권, 쪽수 (미출판은 "In preparation" / "Submitted" / "In revision")
   t    : 제목
   a    : 저자 전체 (공동 제1저자 표시는 이름 뒤에 *, 이름은 쉼표로 구분)
   c    : 교신저자면 true, 아니면 false
   note : (선택) 짧은 메모. 예) note: "Cover article"

   추가하는 법
   - 새로 출판된 논문 : "In prep./submitted" 줄들 바로 아래(= 가장 최근 논문 위)에 한 줄 추가
   - 미출판 논문      : 파일 맨 위 pending 줄들 사이에 추가
   - 미출판 -> 출판    : 해당 줄에서 n, y, ref를 출판 정보로 바꾸고, 출판된 논문 맨 위로 옮기기
   - 위쪽에 있을수록 페이지에서도 위에 나옵니다.
   - 연도 필터 버튼과 "87 published papers" 문구, 논문 수는 자동으로 계산됩니다.
   ============================================================ */
var PUBS = [
    { n: null, y: "pending", ref: "In preparation", t: "Ultrahigh-Loading Intermetallic Pt-Co Alloy Production for High Performance Heavy-Duty Fuel Cells", a: "Jongmin Lee et al.", c: true },
    { n: null, y: "pending", ref: "In preparation", t: "Perception of activity for single atom site electrocatalysts in porous environments", a: "Subin Park et al.", c: true },
    { n: null, y: "pending", ref: "In preparation", t: "Reversible Active-Site Exchange Enables Stability in Single-Atom Catalysts", a: "Jinyeop Kim et al.", c: true },
    { n: null, y: "pending", ref: "Submitted", t: "Decoupling of topological surface states from catalytic activity in the chiral topological semimetal PtGa", a: "Jongkeun Jung et al.", c: false },
    { n: null, y: "pending", ref: "In revision", t: "Regime-Switching Control of C–N Bond Evolution in Electrochemical Methylamine Oxidation", a: "Hanjoo Kim et al.", c: true },
    { n: null, y: "pending", ref: "Submitted", t: "Mechanism-Guided Accelerated Durability Testing of Carbon-Supported Pt Catalysts via Multimodal In Situ Analysis", a: "Hongmin An et al.", c: true },
    { n: null, y: "pending", ref: "In revision", t: "Suppressing Bubble-Induced Nanoparticle Migration Enables Durable Cathodes for AEM Water Electrolysis", a: "Soyeong Jo et al.", c: true },
    { n: null, y: "pending", ref: "Submitted", t: "Unseen but Avoidable: How Impurities Bias Electrocatalysis from Interface to Interpretation", a: "Hongmin An et al.", c: true },
    { n: null, y: "pending", ref: "Submitted", t: "Room-Temperature Synthesis of Transition Metal Nitride Nanocatalysts for Electrochemical Oxygen Evolution", a: "Jin Soo Kang et al.", c: false },
    { n: 87, y: 2026, ref: "Surf. Interfaces 2026, 110345", t: "Operando study of CO₂ adsorption on PtGa (111) surface with ambient pressure XPS", a: "Subin Jang, Minsik Seo, Hyunsuk Shin, Dongwoo Kim, Kyungmin Kim, Hojoon Lim, Hanjoo Kim, Jongkeun Jung, Dong Young Jung, Sung Jong Yoo, Jeongjin Kim, Lenart Dudy, Jean-Jacques Gallet, Fabrice Bournel, Bongjin Simon Mun", c: false },
    { n: 86, y: 2026, ref: "Small 2026 (accepted)", t: "Cu⁺ Driven Formate Selectivity in Oxidation-State-Dependent CO₂ Reduction on Cu₂O/Graphene", a: "Sakthivel Perumal, Taewaen Lim, Kyung Hee Oh, Shin Wook Kang, Jee Hyeon Kim, Hyunseob Lim, Dong Young Chung, Kang-Hyun Park, Ji Chan Park, Junhyeok Seo", c: true },
    { n: 85, y: 2026, ref: "Chem. Eng. J. 2026, 544, 178886", t: "System-Level Impact of Pore Hierarchy and Platinum Spatial Distribution on Performance and Durability", a: "Soyeong Jo, Sohee Kim, Jongmin Lee, Jungwon An, Hyein Park, Jiwoo Lee, Je Hyeon Yeon, Segeun Jang, Dong Young Chung", c: true },
    { n: 84, y: 2026, ref: "ACS Nano 2026, 20, 17490–17500", t: "Insights into native single-atom electrocatalyst site structures", a: "Michael J. Zachman, Hasnain Hafiz, Colum M. O'Leary, Chaewon Lim, Dong Young Chung, Sirui Li, Subin Park, Jiheon Kim, David A. Cullen, Edward F. Holby, Vojislav R. Stamenkovic", c: false },
    { n: 83, y: 2026, ref: "Joule 2026, 10, 102478", t: "Outperforming water electrolysis through catalyst layer structuring with defective 2D mesoporous carbon", a: "Jaeho Byeon, Minkyeong Ban, Liangliang Xu, Seunggeon Lee, Seongbeen Kim, Seonggyu Lee, Seongmin Shin, Donghyeok Son, Wonchul Park, Jinkyu Park, Hoyoung Kim, Dongyoon Woo, Seongseop Kim, Dong Young Chung, Jaewook Nam, Jang Yong Lee, Sungjun Kim, Jinwoo Lee", c: false },
    { n: 82, y: 2026, ref: "JACS Au 2026, 6, 1727–1738", t: "Continuous Glycolic Acid Electrosynthesis Enabled by Ethylene Glycol-Mediated PET Valorization using Nanoporous PdCu Catalysts", a: "Yuanhao Li, Wei-Yi Zhang, Daokun Kang, Qing Zhang, Xianxian Qin, Jinyeop Kim, Jia Wang, Baoxin Ni, Ziyu Ji, Tian-Wen Jiang, Dong Young Chung, Kun Jiang, Wen-Bin Cai", c: false },
    { n: 81, y: 2026, ref: "J. Am. Chem. Soc. 2026, 148, 6045–6056", t: "Dynamic Interface Engineering via Mechanistic Understanding of Copper Reconstruction in Electrochemical CO₂ Reduction Reaction", a: "Hanjoo Kim, Hongmin An, Jinyeop Kim, Hyein Park, Chanwook Cha, Robert Haaring, Hyunjoo Lee, Koohee Han, Dong Young Chung", c: true },
    { n: 80, y: 2026, ref: "J. Mater. Chem. A 2026, 14, 5902–5913", t: "Integrated multiscale structural engineering of Fe–N–C electrocatalysts and device components for high-performance PEMFCs", a: "Seung Yeop Yi, Sanghyeok Lee, Jae Min Kim, Jinyeop Kim, Daeeun Choi, Minkyeong Ban, Dong Yoon Woo, Hyunwoo Jun, Yeju Jang, Jiyoung An, Wonhyeong Lee, Dong Young Chung, Seoin Back, Segeun Jang, Jinwoo Lee", c: false },
    { n: 79, y: 2025, ref: "Chem. Mater. 2025, 37, 7741–7752", t: "Design Principles in Engineering of Multigrain Nanocatalysts via Multiscale Electronic Structure Characterization", a: "Min Gee Cho, Colin Ophus, Jung-Hoon Lee, Inchul Park, Dong Young Chung, Jeong Hyun Kim, Dokyoon Kim, Yung-Eun Sung, Kisuk Kang, Mary C. Scott, A. Paul Alivisatos, Taeghwan Hyeon, Myoung Hwan Oh", c: false },
    { n: 78, y: 2025, ref: "Korean J. Chem. Eng. 2025, 42, 3405–3413", t: "Revealing the Impact of Electronic Conductivity on Iridium-Loaded TiO₂ Catalysts for Efficient Proton Exchange Membrane Water Electrolysis", a: "Wonchul Park, Jongmin Lee, Baeck B. Choi, Ji Hyun Um, Dong Young Chung", c: true },
    { n: 77, y: 2025, ref: "ACS Catal. 2025, 15, 10938", t: "Framework for Reliable Intrinsic Activity Assessment: Separating Electrical Double-Layer Capacitance and Pseudo-Capacitance in Iridium Oxide", a: "Wonchul Park, Jongsu Noh, Hongmin An, Jooyoung Kim, Dong Young Chung", c: true },
    { n: 76, y: 2025, ref: "ACS Energy Lett. 2025, 10, 2574–2581", t: "Operational Stability Factor: A Comprehensive Metric for Assessing Catalyst Durability in Dynamic Water Electrolyzer Conditions", a: "Jinyeop Kim, Jongsu Noh, Dong Young Chung", c: true },
    { n: 75, y: 2025, ref: "J. Am. Chem. Soc. 2025, 147, 16340–16349", t: "Deciphering Catalyst-Support Interaction via Doping for Highly Active and Durable Oxygen Evolution Catalysis", a: "Jinyeop Kim, Jinglong Guo, Nannan Shan, Jimun Yoo, Pedro Farinazzo Bergamo Dias Martins, Jongsu Noh, Moonjung Jung, Peter Zapol, Bongjin Mun, Robert Klie, Pietro Lopes, Nenad Markovic, Dong Young Chung", c: true },
    { n: 74, y: 2025, ref: "ACS Catal. 2025, 15, 7780–7791", t: "The Roles of Ions in Electrochemical Interface for Electrocatalysis", a: "Jongsu Noh, Hanjoo Kim, Hyein Park, Dong Young Chung", c: true },
    { n: 73, y: 2025, ref: "ChemSusChem 2025, 18, e202402763", t: "Improved Chloride Tolerance of Pt Surface by Ionomer Layer Structure Engineering", a: "Jongmin Lee, Jongsu Noh, Vy Thuy Nguyen, Chi-Yeong Ahn, Hyeyoung Shin, Dong Young Chung", c: true },
    { n: 72, y: 2025, ref: "ACS Mater. Au 2025, 1, 1–10", t: "Activity-Stability Relationship in Oxygen Evolution Reaction", a: "Wonchul Park, Dong Young Chung", c: true },
    { n: 71, y: 2024, ref: "EcoMat 2024, e12486", t: "Recommend Practice for Measurement and Evaluation of Oxygen Evolution Reaction Electrocatalysis", a: "Hongmin An, Wonchul Park, Heejong Shin, Dong Young Chung", c: true },
    { n: 70, y: 2024, ref: "ACS Catal. 2024, 14, 8480–8487", t: "Mixed Potential Driven Self-Cleaning Strategy in Direct Isopropanol Fuel Cells", a: "Hanjoo Kim, Dohoon Kim, Jeong-in Son, Segeun Jang, Dong Young Chung", c: true },
    { n: 69, y: 2024, ref: "Chem. Asian J. 2024, e202301016", t: "Investigating Electrode-Ionomer Interface Phenomena for Electrochemical Energy Applications", a: "So Yeong Jo, Hanjoo Kim, Hyein Park, Chi-Yeong Ahn, Dong Young Chung", c: true },
    { n: 68, y: 2023, ref: "J. Am. Chem. Soc. 2023, 145, 16951–16965", t: "Electrochemically activatable liquid organic hydrogen carriers and their applications", a: "Juhyun Cho, Byeongyoon Kim, Sandhya Venkateshalu, Dong Young Chung, Kwangyeol Lee, Sang-Il Choi", c: true },
    { n: 67, y: 2023, ref: "Sustain. Energy Technol. Assess. 2023, 57, 103238", t: "Accelerated stress test of polymer electrolyte membrane water electrolyzer via solar power generation condition", a: "Baeck B. Choi, Jae Hyeon Jo, Young Sung Yoo, Yeong-Jun Choi, Dong Young Chung, Eung-Jun Lee, Sung Jong Yoo", c: true },
    { n: 66, y: 2022, ref: "JACS Au 2022, 2, 2222–2234", t: "Dynamic electrochemical interfaces for energy conversion and storage", a: "Heejong Shin, Ji Mun Yoo, Yung-Eun Sung, Dong Young Chung", c: true },
    { n: 65, y: 2022, ref: "ACS Nano 2022, 16, 16529–16538", t: "Design of metal/oxide/carbon interface for highly active and selective electrocatalysis", a: "Hyunjoong Kim, Ji Mun Yoo, Dong Young Chung, Yongseon Kim, Moonjung Jung, Megalamane S. Bootharaju, Jiheon Kim, Sakang Koo, Heejong Shin, Geumbi Na, Bongjin Simon Mun, Ja Hun Kwak, Yung-Eun Sung, Taeghwan Hyeon", c: true },
    { n: 64, y: 2022, ref: "Microscopy and Microanalysis 2022, S1, 484–486", t: "Imaging Sensitive Catalyst Active Site Structure by 30 keV Electron Ptychography", a: "Michael Zachman, Hasnain Hafiz, Dong Young Chung, Vojislav R. Stamenkovic, Edward F. Holby, David Cullen", c: false },
    { n: 63, y: 2022, ref: "Acc. Chem. Res. 2022, 55, 1278–1289", t: "Carbon Shell on Active Nanocatalyst for Stable Electrocatalysis", a: "Ji Mun Yoo, Heejong Shin, Dong Young Chung, Yung-Eun Sung", c: true },
    { n: 62, y: 2022, ref: "Adv. Sci. 2022, 5, 2104054", t: "Noble Metal-Based Multimetallic Nanoparticles for Electrocatalytic Applications", a: "Hyunjoong Kim, Tae Yong Yoo, Megalamane S. Bootharaju, Jeong Hyun Kim, Dong Young Chung, Taeghwan Hyeon", c: true },
    { n: 61, y: 2021, ref: "Microscopy and Microanalysis 2021, S1, 2976–2977", t: "Atomic-scale Imaging of PGM-free Catalyst Active Sites by 30 keV 4D-STEM", a: "Michael Zachman, Colum M. O'Leary, Dong Young Chung, Hasnain Hafiz, Edward F. Holby, Vojislav R. Stamenkovic, David Cullen", c: false },
    { n: 60, y: 2021, ref: "J. Am. Chem. Soc. 2021, 143, 2741–2750", t: "Dynamically stable active sites from surface evolution of perovskite materials during oxygen evolution reaction", a: "Pietro P. Lopes*, Dong Young Chung*, Xue Rui*, Zheng Hong, Haiying He, Pedro F. B. D. Martins, Dusan Strmcnik, Vojislav R. Stamenkovic, Peter Zapol, J. F. Mitchell, Robert Klie, Nenad M. Markovic", c: false },
    { n: 59, y: 2020, ref: "ACS Energy Lett. 2020, 5, 2827–2834", t: "Activity-Stability Relationship in Au@Pt Nanoparticles for Electrocatalysis", a: "Dong Young Chung, Subin Park, Hyeonju Lee, Hyungjun Kim, Young-Hoon Chung, Ji Mun Yoo, Docheon Ahn, Seung-Ho Yu, Kug-Seung Lee, Mahdi Ahmadi, Huanxin Ju, Hector D. Abruna, Sung Jong Yoo, Bongjin Simon Mun, Yung-Eun Sung", c: false },
    { n: 58, y: 2020, ref: "ACS Catal. 2020, 10, 4990–4996", t: "Electrokinetic analysis of poorly conductive electrocatalytic materials", a: "Dong Young Chung, Subin Park, Pietro P. Lopes, Vojislav R. Stamenkovic, Yung-Eun Sung, Nenad M. Markovic, Dusan Strmcnik", c: false },
    { n: 57, y: 2020, ref: "Nat. Energy 2020, 5, 222–230", t: "Dynamic stability of active sites in hydr(oxy)oxides for the oxygen evolution reaction", a: "Dong Young Chung, Pietro P. Lopes, Pedro F. B. D. Martins, Haiying He, Tomoya Gawaguchi, Peter Zapol, Hoydoo You, Dusan Tripkovic, Dusan Strmcnik, Yisi Zhu, Soenke Seifert, Sungsik Lee, Vojislav R. Stamenkovic, Nenad M. Markovic", c: false },
    { n: 56, y: 2020, ref: "Nature 2020, 577, 359–363", t: "Design and Synthesis of Multigrain Nanocrystals via Geometric Misfit Strain", a: "Myoung Hwan Oh, Min Gee Cho, Dong Young Chung, Inchul Park, Youngwook Paul Kwon, Colin Ophus, Dokyoon Kim, Min Gyu Kim, Beomgyun Jeong, X. Wendy Gu, Jinwoung Jo, Ji Mun Yoo, Jaeyoung Hong, Sara McMains, Kisuk Kang, Yung-Eun Sung, A. Paul Alivisatos, Taeghwan Hyeon", c: false },
    { n: 55, y: 2019, ref: "J. Am. Chem. Soc. 2019, 141, 2035–2045", t: "Design principle of Fe-N-C electrocatalysts: How to optimize multimodal porous structures?", a: "Soo Hong Lee*, Jiheon Kim*, Dong Young Chung*, Ji Mun Yoo, Hyeon Seok Lee, Min Jeong Kim, Bongjin Simon Mun, Soon Gu Kwon, Yung-Eun Sung, Taeghwan Hyeon", c: false, note: "Selected as one of the most highly cited JACS papers of 2018–2019" },
    { n: 54, y: 2019, ref: "Adv. Funct. Mater. 2019, 1909387", t: "Rapid Inversion of Surface Charges in Heteroatom-Doped Porous Carbon: A Route to Robust Electrochemical Desalination", a: "Jin Soo Kang, Seoni Kim, Dong Young Chung, Yoon Jun Son, Kyusik Jo, Xiao Su, Myeong Jae Lee, Hwajoo Joo, T. Alan Hatton, Jeyong Yoon, Yung-Eun Sung", c: false },
    { n: 53, y: 2019, ref: "Microscopy and Microanalysis 2019, 25, 2052–2053", t: "Identical Location STEM analysis on La1-xSrxCoO3 Oxygen-Evolution Catalysts", a: "Xue Rui, Dong Young Chung, Pietro P. Lopes, Hong Zheng, John Mitchell, Nenad M. Markovic, Robert F. Klie", c: false },
    { n: 52, y: 2018, ref: "J. Mater. Chem. A 2018, 6, 20170–20183", t: "Tailoring the porosity of MOF-derived N-doped carbon electrocatalysts for highly efficient solar energy conversion", a: "Jin Soo Kang*, Jiho Kang*, Dong Young Chung*, Yoon Jun Son, Seoni Kim, Sungjun Kim, Juwon Jeong, Myeong Jae Lee, Heejon Shin, Subin Park, Sung Jong Yoo, Min Jae Ko, Jeyong Yoon, Kwon, Yung-Eun Sung", c: false },
    { n: 51, y: 2018, ref: "Small 2018, 14, 1802191", t: "Edge-terminated MoS₂ nano-assembled electrocatalyst via in situ hybridization with three-dimensional carbon network", a: "Dong Young Chung, Ji Mun Yoo, Subin Park, Gwan Yeong Jung, Jin Soo Kang, Chi-Yeong Ahn, Sang Kyu Kwak, Yung-Eun Sung", c: false },
    { n: 50, y: 2018, ref: "Adv. Mater. 2018, 30, 1704123", t: "Highly durable and active Pt-based nanoscale design for oxygen reduction fuel cell electrocatalyst", a: "Dong Young Chung, Ji Mun Yoo, Yung-Eun Sung", c: false },
    { n: 49, y: 2018, ref: "Appl. Catal. B: Environ. 2018, 227, 409–417", t: "Highly loaded PbS/Mn-doped CdS quantum dots for dual application in solar-to-electrical and solar-to-chemical energy conversion", a: "Jae-Yup Kim, Youn Jeong Jang, Jongwoo Park, Jeehye Kim, Jin Soo Kang, Dong Young Chung, Changhee Lee, Jae Sung Lee, Min Jae Ko", c: false },
    { n: 48, y: 2018, ref: "Adv. Energy Mater. 2018, 1703114", t: "Room-Temperature Vapor Deposition of Cobalt Nitride Nanofilms for Mesoscopic and Perovskite Solar Cells", a: "Jin Soo Kang, Jae-Yup Kim, Jungjin Yoon, Jiwoong Yang, Dong Young Chung, Min-Cheol Kim, Hansol Jeong, Yoon Jun Son, Bong Gyu Kim, Juwon Jeong, Taeghwan Hyeon, Mansoo Choi, Min Jae Ko, Yung-Eun Sung", c: false },
    { n: 47, y: 2017, ref: "ACS Appl. Mater. Interfaces 2017, 9, 41303–41313", t: "Coffee Waste-Derived Hierarchical Porous Carbon as a Highly Active and Durable Electrocatalyst for Electrochemical Energy Applications", a: "Dong Young Chung, Yoon Jun Son, Ji Mun Yoo, Jin Soo Kang, Chi-Yeong Ahn, Subin Park, Yung-Eun Sung", c: false },
    { n: 46, y: 2017, ref: "J. Am. Chem. Soc. 2017, 139, 6669–6674", t: "Large-scale Synthesis of Carbon Shell-coated FeP Nanoparticles for Robust Hydrogen Evolution Reaction Electrocatalyst", a: "Dong Young Chung, Samuel Woojoo Jun, Gabin Yoon, Hyunjoong Kim, Ji Mun Yoo, Kug-Seung Lee, Taehyun Kim, Heejong Shin, Arun Kumar Sinha, Soon Gu Kwon, Kisuk Kang, Taeghwan Hyeon, Yung-Eun Sung", c: false },
    { n: 45, y: 2017, ref: "Chem. Mater. 2017, 29, 2890–2898", t: "Low-Temperature and Gram-Scale Synthesis of Two-Dimensional Fe-N-C Carbon Sheets for Robust Electrochemical Oxygen Reduction Reaction", a: "Dong Young Chung, Min Jeong Kim, Narae Kang, Ji Mun Yoo, Heejong Shin, Ok-Hee Kim, Yung-Eun Sung", c: false },
    { n: 44, y: 2017, ref: "Catal. Today 2017, 293, 2–7", t: "CO electro-oxidation reaction on Pt nanoparticles: understanding peak multiplicity through thiol derivative molecule adsorption", a: "Dong Young Chung, Myeong Jae Lee, Minhyoung Kim, Heejong Shin, Mi-Ju Kim, Ji Mun Yoo, Subin Park, Yung-Eun Sung", c: false },
    { n: 43, y: 2017, ref: "Adv. Sci. 2017, 5, 1700601", t: "Electrochemically Synthesized Nanoporous Molybdenum Carbide as a Durable Electrocatalyst for Hydrogen Evolution Reaction", a: "Jin Soo Kang, Jin Kim, Myeong Jae Lee, Yoon Jun Son, Dong Young Chung, Subin Park, Juwon Jeong, Ji Mun Yoo, Heejong Shin, Heeman Choe, Hyun S. Park, Yung-Eun Sung", c: false },
    { n: 42, y: 2017, ref: "ChemSusChem 2017, 10, 3063–3068", t: "Self-Assembled Dendritic Pt Nanostructure with High-index Facets as Highly active and Durable Electrocatalyst for Oxygen Reduction", a: "Youngjin Jang, Kwang-Hyun Choi, Dong Young Chung, Ji Eun Lee, Namgee Jung, Yung-Eun Sung", c: false },
    { n: 41, y: 2017, ref: "Electrochim. Acta 2017, 245, 219–226", t: "Lithium manganese phosphate-carbon composite as a highly active and durable electrocatalyst for oxygen reduction reaction", a: "Myeong Jae Lee, Jin Soo Kang, Docheon Ahn, Dong Young Chung, Subin Park, Yoon Jun Son, Ji Mun Yoo, Heejong Shin, Yun Sik Kang, Nark-Eon Sung, Kug-Seung Lee, Yung-Eun Sung", c: false },
    { n: 40, y: 2017, ref: "Nanoscale 2017, 9, 5413–5424", t: "Electrochemical synthesis of nanoporous tungsten carbide and its application as electrocatalysts for photoelectrochemical cells", a: "Jin Soo Kang, Jin Kim, Myeong Jae Lee, Yoon Jun Son, Juwon Jeong, Dong Young Chung, Ahyoun Lim, Heeman Choe, Hyun S. Park, Yung-Eun Sung", c: false },
    { n: 39, y: 2017, ref: "ACS Appl. Mater. Interfaces 2017, 9, 8519–8532", t: "High Density Single-layer Coating of Gold Nanoparticles onto Multiple Substrates by Using an Intrinsically Disordered Protein of α-Synuclein for Nano Applications", a: "Ghibom Bhak, Junghee Lee, Chang-Hyun Kim, Dong Young Chung, Jin Hyoun Kang, Soojung Oh, Jungsup Lee, Jin Soo Kang, Ji Mun Yoo, Jee Eun Yang, Kun Yil Rhoo, Sunghak Park, Somin Lee, Ki Tae Nam, Noo Li Jeon, Jyongsik Jang, Byung Hee Hong, Yung-Eun Sung, Myung-Han Yoon, Seung R. Paik", c: false },
    { n: 38, y: 2016, ref: "J. Power Sources 2016, 334, 52–57", t: "Functional link between surface low-coordination sites and the electrochemical durability of Pt nanoparticles", a: "Dong Young Chung, Heejong Shin, Ji Mun Yoo, Kug-Seung Lee, Nam-Suk Lee, Kisuk Kang, Yung-Eun Sung", c: false },
    { n: 37, y: 2016, ref: "J. Mater. Chem. A 2016, 4, 12720–12725", t: "Three-dimensional carbon foam/graphene@MoS₂ hybrid nanostructures as effective electrocatalysts for hydrogen evolution reaction", a: "Seung-Keun Park*, Dong Young Chung*, Dongjin Ko, Yung-Eun Sung, Yuanzhe Piao", c: false },
    { n: 36, y: 2016, ref: "J. Phys. Chem. C 2016, 120, 9028–9035", t: "Methanol Electro-Oxidation on the Pt Surface: Revisiting the Cyclic Voltammetry Interpretation", a: "Dong Young Chung, Kyung-Jae Lee, Yung-Eun Sung", c: false },
    { n: 35, y: 2016, ref: "J. Phys. Chem. C 2016, 120, 24511–24520", t: "Charting Outer Helmholtz Plane and the Role of Nitrogen Doping in the Oxygen Reduction Reaction Conducted in Alkaline Media Using Non-precious Metal Catalysts", a: "Stanfield Youngwon Lee, Dong Young Chung, Myeong Jae Lee, Yun Sik Kang, Heejong Shin, Mi-Ju Kim, Christopher W. Bielawski, Yung-Eun Sung", c: false },
    { n: 34, y: 2016, ref: "ACS Catal. 2016, 6, 3914–3920", t: "Scaffold-Like Titanium Nitride Nanotubes with a Highly Conductive Porous Architecture as a Nanoparticle Catalyst Support for Oxygen Reduction", a: "Heejong Shin, Hyoung-il Kim, Dong Young Chung, Ji Mun Yoo, Seunghyun Weon, Wonyong Choi, Yung-Eun Sung", c: false },
    { n: 33, y: 2016, ref: "ACS Catal. 2016, 6, 2398–2407", t: "Understanding the Bifunctional Effect for Removal of CO Poisoning: Blend of a Platinum Nanocatalyst and Hydrous Ruthenium Oxide as a Model System", a: "Myeong Jae Lee, Jin Soo Kang, Yun Sik Kang, Dong Young Chung, Heejong Shin, Chi-Yeong Ahn, Subin Park, Mi-Ju Kim, Sungjun Kim, Kug-Seung Lee, Yung-Eun Sung", c: false },
    { n: 32, y: 2016, ref: "Carbon 2016, 105, 1–7", t: "Nitrogen and boron co-doped hollow carbon catalyst for the oxygen reduction reaction", a: "Ji-Sun Han, Dong Young Chung, Dae-Gwon Ha, Jin-Hong Kim, Keunsu Choi, Yung-Eun Sung, Shin-Hoo Kang", c: false },
    { n: 31, y: 2016, ref: "J. Power Sources 2016, 303, 234–242", t: "Effect of post heat-treatment of composition-controlled PdFe nanoparticles for oxygen reduction reaction", a: "Yun Sik Kang, Kwang-Hyun Choi, Docheon Ahn, Myeong Jae Lee, Jaeyoon Baik, Dong Young Chung, Mi-Ju Kim, Stanfield Youngwon Lee, Minhyoung Kim, Heejong Shin, Kug-Seung Lee, Yung-Eun Sung", c: false },
    { n: 30, y: 2016, ref: "NPG Asia Mater. 2016, 8, e237", t: "Electronic Ensemble Effects of Organic/Inorganic Hybrid Surface on PtCo Nanoparticles for Oxygen Reduction Reactions", a: "Namgee Jung, Satadeep Bhattacharjee, Sanjeev Gautam, Hee-Young Park, Jaeyune Ryu, Young-Hoon Chung, Sang-Young Lee, Injoon Jang, Jong-Hyun Jang, Sae Hum Park, Dong Young Chung, Yung-Eun Sung, Keun-Hwa Chae, Umesh V. Waghmare, Seung-Cheol Lee, Sung Jong Yoo", c: false },
    { n: 29, y: 2015, ref: "J. Am. Chem. Soc. 2015, 137, 15478–15485", t: "Highly durable and active PtFe nanocatalyst for electrochemical oxygen reduction reaction", a: "Dong Young Chung, Samuel Woojoo Jun, Gabin Yoon, Soon Gu Kwon, Dong Yun Shin, Pilseon Seo, Ji Mun Yoo, Heejong Shin, Young-Hoon Chung, Hyungjoong Kim, Bongjin Simon Mun, Kug-Seung Lee, Nam-Suk Lee, Sung Jong Yoo, Donghee Lim, Kisuk Kang, Yung-Eun Sung, Taeghwan Hyeon", c: false },
    { n: 28, y: 2015, ref: "Chem. Commun. 2015, 52, 597–600", t: "Simple synthesis of urchin-like Pt-Ni bimetallic nanostructures as enhanced electrocatalyst for oxygen reduction reaction", a: "Kwang-Hyun Choi*, Youngjin Jang*, Dong Young Chung*, Pilseon Seo, Samuel Woojoo Jun, Ji Eun Lee, Myoung Hwan Oh, Sung Jong Yoo, Yung-Eun Sung, Taeghwan Hyeon", c: false },
    { n: 27, y: 2015, ref: "J. Phys. Chem. C 2015, 119, 9169–9176", t: "Understanding interface between electrode and electrolyte: Organic/inorganic hybrid design for fast ion conductivity", a: "Dong Young Chung, Young-Hoon Chung, Sungmin Kim, Ju Wan Lim, Kyung Jae Lee, Namgee Jung, Hyeyoung Shin, Ok-Hee Kim, Hyungjun Kim, Sung Jong Yoo, Yung-Eun Sung", c: false },
    { n: 26, y: 2015, ref: "Nanoscale 2015, 5, 5157–5163", t: "Structure dependent active sites of NixSy as an electrocatalysts for hydrogen evolution reaction", a: "Dong Young Chung, Jung Woo Han, Dong-Hee Lim, Jun-Ho Jo, Sung Jong Yoo, Hyunjoo Lee, Yung-Eun Sung", c: false },
    { n: 25, y: 2015, ref: "Adv. Energy Mater. 2015, 5, 1401309", t: "Alveoli-inspired Facile Transport Structure of N-Doped Porous Carbon for Electrochemical Energy Applications", a: "Dong Young Chung, Kyungjae Lee, Seung-Ho Yu, Minhyeong Kim, Stanfield Youngwon Lee, Ok-Hee Kim, Yung-Eun Sung", c: false },
    { n: 24, y: 2015, ref: "Sci. Rep. 2015, 5, 10450", t: "Reactively sputtered nickel nitride as electrocatalytic counter electrode for dye-and quantum dot-sensitized solar cells", a: "Jin Soo Kang, Min-Ah Park, Jae-Yup Kim, Sun Ha Park, Dong Young Chung, Seung-Ho Yu, Jin Kim, Jongwoo Park, Jung-Woo Choi, Kyung Jae Lee, Juwon Jeong, Min Jae Ko, Kwang-Soon Ahn, Yung-Eun Sung", c: false },
    { n: 23, y: 2015, ref: "Appl. Catal. B: Environ. 2015, 174, 35–42", t: "Electronic structure modification of platinum on titanium nitride resulting in enhanced catalytic activity and durability for oxygen reduction and formic acid oxidation", a: "Sungeun Yang, Dong Young Chung, Young-Joo Tak, Jiwhan Kim, Haksu Han, Jong-Sung Yu, Aloysius Soon, Yung-Eun Sung, Hyunjoo Lee", c: false },
    { n: 22, y: 2015, ref: "Electrochim. Acta 2015, 164, 235–242", t: "Enhanced Methanol Tolerance of Highly Pd rich Pd-Pt Cathode Electrocatalysts in Direct Methanol Fuel Cells", a: "Baeck Choi, Woo-Hyun Nam, Dong Young Chung, In-Su Park, Sung Jong Yoo, Jae Chun Song, Yung-Eun Sung", c: false },
    { n: 21, y: 2015, ref: "Sci. Rep. 2015, 5, 8376", t: "Facile and Gram-scale Synthesis of Metal-free Catalysts: Toward Realistic Applications for Fuel Cells", a: "Ok-Hee Kim, Yong-Hun Cho, Dong Young Chung, Minjeong Kim, Ji Mun Yoo, Ji Eun Park, Heeman Choe, Yung-Eun Sung", c: false },
    { n: 20, y: 2015, ref: "Chem. Commun. 2015, 51, 2968–2971", t: "Third-body effects of native surfactants on Pt nanoparticle electrocatalysts in proton exchange fuel cells", a: "Young-Hoon Chung, Soo Jin Kim, Dong Young Chung, Hee Young Park, Yung-Eun Sung, Sung Jong Yoo, Jong Hyun Jang", c: false },
    { n: 19, y: 2015, ref: "Electrochim. Acta 2015, 151, 256–262", t: "Titanium Silicide Coated Porous Silicon Nanospheres as Anode Materials for Lithium Ion Batteries", a: "Young Min Kim, Jihoon Ahn, Seung-Ho Yu, Dong Young Chung, Kyung Jae Lee, Jin-Kyu Lee, Yung-Eun Sung", c: false },
    { n: 18, y: 2014, ref: "J. Electrochem. Sci. Technol. 2014, 5, 65–72", t: "Electrocatalyst for the Oxygen Reduction Reaction: from the nanoscale to the Macroscale", a: "Dong Young Chung, Yung-Eun Sung", c: false },
    { n: 17, y: 2014, ref: "Sci. Rep. 2014, 4, 7450", t: "Inhibition of CO poisoning on Pt catalyst coupled with the reduction of toxic hexavalent chromium in a dual-functional fuel cell", a: "Dong Young Chung, Hyoung-il Kim, Young-Hoon Chung, Sung Jong Yoo, Wonyong Choi, Yung-Eun Sung", c: false },
    { n: 16, y: 2014, ref: "Nano Today 2014, 9, 433–456", t: "Pt-based nanoarchitecture and catalyst design for fuel cell applications", a: "Namgee Jung*, Dong Young Chung*, Jaeyune Ryu, Sung Jong Yoo, Yung-Eun Sung", c: false },
    { n: 15, y: 2014, ref: "Nanoscale 2014, 6, 2131–2136", t: "Edge-exposed MoS₂ nano-assembled structures as an efficient electrocatalyst for hydrogen evolution reaction", a: "Dong Young Chung, Seung-Keun Park, Young-Hoon Chung, Seung-Ho Yu, Dong-Hee Lim, Namgee Jung, Hyung Chul Ham, Hee-Young Park, Yuanzhe Piao, Sung Jong Yoo, Yung-Eun Sung", c: false },
    { n: 14, y: 2014, ref: "Int. J. Hydrogen Energy 2014, 39, 14751–14759", t: "Effects of surface composition of Pt-Fe nanoparticles for oxygen reduction reactions", a: "Young-Hoon Chung, Dong Young Chung, Namgee Jung, Hee-Young Park, Yung-Eun Sung", c: false },
    { n: 13, y: 2014, ref: "RSC Adv. 2014, 4, 37365–37370", t: "Facile synthesis of nanostructural carbon nanotubes/iron oxide hybrids for lithium-ion battery anodes", a: "Seung-Ho Yu, Xiaohui Guo, Daishun Ling, Dong Young Chung, Aihua Jin, Mohammadreza Shokouhimehr, Taeghwan Hyeon, Yung-Eun Sung", c: false },
    { n: 12, y: 2014, ref: "J. Phys. Chem. C 2014, 118, 9939–9945", t: "Origin of the Enhanced Electrocatalysis for Thermally Controlled Nanostructure of Bimetallic Nanoparticles", a: "Young-Hoon Chung, Dong Young Chung, Namgee Jung, Hee Young Park, Sung Jong Yoo, Jong Hyun Jang, Yung-Eun Sung", c: false },
    { n: 11, y: 2014, ref: "Phys. Chem. Chem. Phys. 2014, 16, 13726–13732", t: "Tuning the Oxygen Reduction Activity of the Pt-Ni Nanoparticles by varying Heat Treatment Atmosphere under Specific Anion Adsorption", a: "Young-Hoon Chung, Soo Jin Kim, Dong Young Chung, Myeong Jae Lee, Jong Hyun Jang, Yung-Eun Sung", c: false },
    { n: 10, y: 2014, ref: "Sci. Rep. 2014, 4, 5639", t: "Single Source Precursor-based Solvothermal Synthesis of Heteroatom-doped Graphene and Its Energy Storage and Conversion Applications", a: "Bo Quan, Seung-Ho Yu, Dong Young Chung, Aihua Jin, Yung-Eun Sung, Yuanzhe Piao", c: false },
    { n: 9, y: 2014, ref: "Appl. Catal. B: Environ. 2014, 154, 309–315", t: "PtPdCo ternary electrocatalyst for methanol tolerant oxygen reduction reaction in direct methanol fuel cell", a: "Yoon-Hwan Cho, Ok-Hee Kim, Dong Young Chung, Heeman Choe, Yong-Hun Cho, Yung-Eun Sung", c: false },
    { n: 8, y: 2013, ref: "Phys. Chem. Chem. Phys. 2013, 15, 13658–13663", t: "Correlation between Platinum nanoparticle surface rearrangement induced by heat treatment and activity for an oxygen reduction reaction", a: "Dong Young Chung, Young-Hoon Chung, Namgee Jung, Kwang-Hyun Choi, Yung-Eun Sung", c: false },
    { n: 7, y: 2013, ref: "Nat. Commun. 2013, 4, 2473", t: "Ordered macroporous platinum electrode and enhanced mass transfer in fuel cells using inverse opal structure", a: "Ok-Hee Kim, Yong-Hun Cho, Soon-Hyung Kang, Hee-Young Park, Minhyoung Kim, Ju Wan Lim, Dong Young Chung, Myeong Jae Lee, Heeman Choe, Yung-Eun Sung", c: false },
    { n: 6, y: 2013, ref: "Phys. Chem. Chem. Phys. 2013, 15, 17079–17083", t: "Chemical tuning of electrochemical properties of Pt-skin surface for highly active oxygen reduction reaction", a: "Namgee Jung, Young-Hoon Chung, Dong Young Chung, Kwang-Hyun Choi, Hee-Young Park, Jaeyune Ryu, Sang-Young Lee, Mansu Kim, Yung-Eun Sung, Sung Jong Yoo", c: false },
    { n: 5, y: 2013, ref: "J. Phys. Chem. Lett. 2013, 4, 1304–1309", t: "Tailoring the Electronic Structure of Nanoelectrocatalysts Induced by a Surface-Capping Organic Molecule for the Oxygen Reduction Reaction", a: "Young-Hoon Chung, Dong Young Chung, Namgee Jung, Yung-Eun Sung", c: false },
    { n: 4, y: 2013, ref: "Chem. Mater. 2013, 25, 1526–1532", t: "High-Performance Hybrid Catalyst with Selectively Functionalized Carbon by Temperature-Directed Switchable Polymer", a: "Namgee Jung, Sang Moon Kim, Do Hyun Kang, Dong Young Chung, Yun Sik Kang, Young-Hoon Chung, Yong Whan Choi, Changhyun Pang, Kahp-Yang Suh, Yung-Eun Sung", c: false },
    { n: 3, y: 2012, ref: "Int. J. Hydrogen Energy 2012, 37, 11969–11974", t: "Improved mass transfer using a pore former in cathode catalyst layer in the direct methanol fuel cell", a: "Yoon-Hwan Cho, Namgee Jung, Yun Sik Kang, Dong Young Chung, Ju Wan Lim, Heeman Choe, Yong-Hun Cho, Yung-Eun Sung", c: false },
    { n: 2, y: 2012, ref: "J. Electrochem. Soc. 2012, 159, B378–B384", t: "Ionic Resistance of a Cathode Catalyst Layer with Various Thicknesses by Electrochemical Impedance Spectroscopy for PEMFC", a: "Ju Wan Lim, Yong-Hun Cho, Minjeh Ahn, Dong Young Chung, Yoon-Hwan Cho, Namgee Jung, Yun Sik Kang, Ok-Hee Kim, Myeong Jae Lee, Minhyoung Kim, Yung-Eun Sung", c: false },
    { n: 1, y: 2011, ref: "Int. J. Hydrogen Energy 2011, 36, 15731–15738", t: "Methanol-tolerant cathode electrode structure composed of heterogeneous composites to overcome methanol crossover effects for direct methanol fuel cell", a: "Namgee Jung, Yoon-Hwan Cho, Minjeh Ahn, Ju Wan Lim, Yun Sik Kang, Dong Young Chung, Jinho Kim, Yong-Hun Cho, Yung-Eun Sung", c: false }
];
